Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("HALLEY'S COMET");
Console.ReadKey();

Console.ResetColor();
Console.WriteLine("I don't want it");
Console.ReadKey();
Console.WriteLine("And I don't want to want you");
Console.ReadKey();
Console.WriteLine("But in my dreams, I seem to be more honest");
Console.ReadKey();
Console.WriteLine("And I must admit you've been in quite a few");
Console.ReadKey();
Console.WriteLine("Halley's Comet");
Console.ReadKey();
Console.WriteLine("Comes around more than I do");
Console.ReadKey();
Console.WriteLine("But you're all it takes for me to break a promise");
Console.ReadKey();
Console.WriteLine("Silly me to fall in love with you");
Console.ReadKey();
Console.WriteLine("I haven't slept since Sunday");
Console.ReadKey();
Console.WriteLine("Midnight for me is 3AM for you");
Console.ReadKey();
Console.WriteLine("But my sleepless nights are better");
Console.ReadKey();
Console.WriteLine("With you than nights could ever be alone, ooh-ooh");
Console.ReadKey();
Console.WriteLine("I was good at feeling nothin', now I'm hopeless");
Console.ReadKey();
Console.WriteLine("What a drag to love you like I do");
Console.ReadKey();
Console.WriteLine("Ooh-ooh-ooh-ooh-ooh");
Console.ReadKey();
Console.WriteLine("I've been loved before, but right now, in this moment");
Console.ReadKey();
Console.WriteLine("I feel more and more like I was made for you");
Console.ReadKey();
Console.WriteLine("For you");
Console.ReadKey();
Console.WriteLine("I'm sitting in my brother's room");
Console.ReadKey();
Console.WriteLine("Haven't slept in a week or two, or two");
Console.ReadKey();
Console.WriteLine("I think I might have fallen in love");
Console.ReadKey();
Console.WriteLine("What am I to do?");
